# Generated by Django 4.2.7 on 2024-03-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
