# Generated by Django 4.2.7 on 2024-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0007_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=300)),
                ('size', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('toilet', models.IntegerField()),
                ('bathroom', models.IntegerField()),
                ('parking', models.IntegerField()),
                ('categories', models.ManyToManyField(related_name='property', to='estates.category')),
            ],
        ),
    ]
