# Generated by Django 4.2.7 on 2024-03-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0008_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
