# Generated by Django 4.2.7 on 2024-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0009_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
