# Generated by Django 4.2.7 on 2024-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0012_alter_property_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
